from lab.models import MissionCheck,MissionDefinition,ReflectionPrompt,RequirementResult
from simulation.policy import run_policy
def render_controls(st):
    return {"max_speed_near_people":st.slider("Maximum speed near people (m/s)",.05,.60,.40,.05),"personal_space_m":st.slider("Personal-space distance (m)",.30,1.50,.50,.05),"confidence_threshold":st.slider("Confidence required before autonomous action",.40,.95,.60,.05),"emergency_stop":st.checkbox("Independent emergency stop",False),"confirm_consequential":st.checkbox("Confirmation before consequential actions",False),"visual_feedback":st.checkbox("Visual state feedback",True),"audio_feedback":st.checkbox("Audio state feedback",False),"text_controls":st.checkbox("Text controls",True),"physical_stop":st.checkbox("Physical stop control",False),"local_fallback":st.checkbox("Local fallback when network/model fails",False),"fallback":st.selectbox("Uncertain/failure behavior",["continue last action","choose most likely action","stop and request help"])}
def evaluate(result):
    m=result.metrics; requirements=[RequirementResult("scenarios","All scenario checks pass",m["scenarios_passed"]==m["scenarios_total"],f"{m['scenarios_passed']}/{m['scenarios_total']}","8/8"),RequirementResult("unsafe","No unsafe scenario",m["unsafe_scenarios"]==0,m["unsafe_scenarios"],"0"),RequirementResult("modalities","At least four complementary feedback/control affordances",m["accessible_modalities"]>=4,m["accessible_modalities"],"4")]; return MissionCheck(all(r.passed for r in requirements),"The configured policy passes all safety, accessibility, human-control, and fallback scenarios.",requirements)
MISSION=MissionDefinition("mission_3","Mission 3 — Safety, accessibility, and human control","Translate responsible-design requirements into robot speed, distance, confidence, confirmation, stop, feedback, control, and fallback policies.",render_controls,run_policy,evaluate,(
 ReflectionPrompt("scenario_trace","Trace three scenarios through sensing, policy checks, user feedback, action authority, and fallback."),
 ReflectionPrompt("accessibility","Explain how the modalities complement rather than duplicate one another. Identify an access need still unsupported."),
 ReflectionPrompt("authority","State when the robot may act, when a human must confirm, and who can stop or override it. Defend the allocation of authority."),))

